### ISSUE TITLE
Non descriptive image of the project on README.md

### ISSUE THREAD

**Issue by Payll** [Payll/Intelligo#4]
Find a logo and set the README !

**Comment by RonanEtudes** [comment]
yes i agree with that

**Comment by Slonev0** [comment]
dear collaborator, 

I also agree with that idea, please do it ASAP

Sincerely yours, 

M.Voisin

**Comment by Slonev0** [comment]
you can close this now

Lovely yours,

Enzo

**Comment by Payll** [comment]
fixe with #6
